-- Phase 1 starter schema for the Trend-to-Domain Intelligence System.

create table if not exists portfolio_domains (
    id bigint generated by default as identity primary key,
    full_domain text not null unique,
    name text not null,
    ext text not null,
    niche text default '',
    appraisal_tier text default '',
    appraisal_value text default '',
    score integer default 0,
    scoring_profile text default '',
    explanation text default '',
    status text default 'Not checked',
    generated_date text default '',
    purchased_date text default ''
);

create table if not exists content_items (
    id bigint generated by default as identity primary key,
    source_name text not null,
    source_type text not null,
    title text not null,
    url text not null unique,
    body text default '',
    summary text default '',
    author text default '',
    language text default 'en',
    content_hash text not null unique,
    cluster_key text default '',
    cluster_terms jsonb default '[]'::jsonb,
    classification text default '',
    theme_name text default '',
    theme_description text default '',
    signal_score double precision default 0,
    published_at timestamptz,
    fetched_at timestamptz not null,
    processed_at timestamptz,
    tags jsonb default '[]'::jsonb,
    reasons jsonb default '[]'::jsonb,
    raw_payload jsonb default '{}'::jsonb,
    is_processed boolean default false,
    ingest_run_id text default '',
    processed_run_id text default ''
);

alter table content_items add column if not exists cluster_terms jsonb default '[]'::jsonb;
alter table content_items add column if not exists classification text default '';
alter table content_items add column if not exists theme_name text default '';
alter table content_items add column if not exists theme_description text default '';
alter table content_items add column if not exists signal_score double precision default 0;
alter table content_items add column if not exists processed_at timestamptz;
alter table content_items add column if not exists reasons jsonb default '[]'::jsonb;
alter table content_items add column if not exists is_processed boolean default false;
alter table content_items add column if not exists ingest_run_id text default '';
alter table content_items add column if not exists processed_run_id text default '';

create index if not exists idx_content_items_is_processed on content_items (is_processed);
create index if not exists idx_content_items_theme_name on content_items (theme_name);

create table if not exists themes (
    id bigint generated by default as identity primary key,
    canonical_name text not null unique,
    description text default '',
    classification text not null,
    source_count integer default 0,
    first_seen_at timestamptz not null,
    last_seen_at timestamptz not null,
    momentum_score double precision default 0,
    related_terms jsonb default '[]'::jsonb,
    source_names jsonb default '[]'::jsonb,
    source_types jsonb default '[]'::jsonb,
    source_tags jsonb default '[]'::jsonb,
    source_entities jsonb default '[]'::jsonb,
    source_breakdown jsonb default '[]'::jsonb,
    cluster_keys jsonb default '[]'::jsonb,
    evidence_titles jsonb default '[]'::jsonb,
    reason_highlights jsonb default '[]'::jsonb
);

alter table themes add column if not exists source_names jsonb default '[]'::jsonb;
alter table themes add column if not exists source_types jsonb default '[]'::jsonb;
alter table themes add column if not exists source_tags jsonb default '[]'::jsonb;
alter table themes add column if not exists source_entities jsonb default '[]'::jsonb;
alter table themes add column if not exists source_breakdown jsonb default '[]'::jsonb;
alter table themes add column if not exists cluster_keys jsonb default '[]'::jsonb;
alter table themes add column if not exists evidence_titles jsonb default '[]'::jsonb;
alter table themes add column if not exists reason_highlights jsonb default '[]'::jsonb;

create table if not exists keywords (
    id bigint generated by default as identity primary key,
    keyword text not null,
    keyword_type text not null,
    theme_name text not null,
    classification text not null,
    niche text default '',
    buyer_type text default '',
    commercial_score double precision default 0,
    novelty_score double precision default 0,
    brandability_score double precision default 0,
    notes text default ''
);

create unique index if not exists idx_keywords_theme_keyword_type
on keywords (theme_name, keyword, keyword_type);

create table if not exists domain_ideas (
    id bigint generated by default as identity primary key,
    domain_name text not null,
    extension text not null,
    source_theme text not null,
    recommendation text not null,
    keyword text default '',
    niche text default '',
    buyer_type text default '',
    style text default '',
    score double precision default 0,
    review_bucket text default '',
    scoring_profile text default '',
    grade text default '',
    value_estimate text default '',
    rationale text default '',
    risk_notes jsonb default '[]'::jsonb,
    rejected_reason text default ''
);

alter table domain_ideas add column if not exists scoring_profile text default '';
alter table domain_ideas add column if not exists grade text default '';
alter table domain_ideas add column if not exists value_estimate text default '';
alter table domain_ideas add column if not exists review_bucket text default '';

create unique index if not exists idx_domain_ideas_theme_domain_extension
on domain_ideas (source_theme, domain_name, extension);

create index if not exists idx_domain_ideas_review_bucket
on domain_ideas (review_bucket);

create table if not exists runs (
    id bigint generated by default as identity primary key,
    run_id text not null unique,
    job_name text not null,
    status text not null,
    started_at timestamptz not null,
    ended_at timestamptz,
    notes text default ''
);
