-- Phase 1 starter schema for the Trend-to-Domain Intelligence System.

create table if not exists portfolio_domains (
    id bigint generated by default as identity primary key,
    full_domain text not null unique,
    name text not null,
    ext text not null,
    niche text default '',
    appraisal_tier text default '',
    appraisal_value text default '',
    score integer default 0,
    scoring_profile text default '',
    explanation text default '',
    status text default 'Not checked',
    generated_date text default '',
    purchased_date text default ''
);

create table if not exists content_items (
    id bigint generated by default as identity primary key,
    source_name text not null,
    source_type text not null,
    title text not null,
    url text not null unique,
    body text default '',
    summary text default '',
    author text default '',
    language text default 'en',
    content_hash text not null unique,
    published_at timestamptz,
    fetched_at timestamptz not null,
    tags jsonb default '[]'::jsonb,
    raw_payload jsonb default '{}'::jsonb
);

create table if not exists themes (
    id bigint generated by default as identity primary key,
    canonical_name text not null unique,
    description text default '',
    classification text not null,
    source_count integer default 0,
    first_seen_at timestamptz not null,
    last_seen_at timestamptz not null,
    momentum_score double precision default 0,
    related_terms jsonb default '[]'::jsonb
);

create table if not exists keywords (
    id bigint generated by default as identity primary key,
    keyword text not null,
    keyword_type text not null,
    theme_name text not null,
    classification text not null,
    niche text default '',
    buyer_type text default '',
    commercial_score double precision default 0,
    novelty_score double precision default 0,
    brandability_score double precision default 0,
    notes text default ''
);

create table if not exists domain_ideas (
    id bigint generated by default as identity primary key,
    domain_name text not null,
    extension text not null,
    source_theme text not null,
    recommendation text not null,
    keyword text default '',
    niche text default '',
    buyer_type text default '',
    style text default '',
    score double precision default 0,
    rationale text default '',
    risk_notes jsonb default '[]'::jsonb,
    rejected_reason text default ''
);

create table if not exists runs (
    id bigint generated by default as identity primary key,
    run_id text not null unique,
    job_name text not null,
    status text not null,
    started_at timestamptz not null,
    ended_at timestamptz,
    notes text default ''
);
